DNS_A = 1, // a host address
DNS_NS = 2, // an authoritative name server
DNS_MD = 3, // a mail destination (Obsolete - use MX)
DNS_MF = 4, // a mail forwarder (Obsolete - use MX)
DNS_CNAME = 5, // the canonical name for an alias
DNS_SOA = 6, // marks the start of a zone of authority
DNS_MB = 7, // a mailbox domain name (EXPERIMENTAL)
DNS_MG = 8, // a mail group member (EXPERIMENTAL)
DNS_MR = 9, // a mail rename domain name (EXPERIMENTAL)
DNS_NULL = 10, // a null RR (EXPERIMENTAL)
DNS_WKS = 11, // a well known service description
DNS_PTR = 12, // a domain name pointer
DNS_HINFO = 13, // host information
DNS_MINFO = 14, // mailbox or mail list information
DNS_MX = 15, // mail exchange
DNS_TXT = 16, // text strings