<?php
$max_args = 20;

function callsite(array& $types): string
{
	$nargs = count($types) - 1;

	$str = $types[0] == 0 ? "reinterpret_cast<uintptr_t(*)(" : "reinterpret_float_to_int(reinterpret_cast<double(*)(";
	for ($i = 0; $i != $nargs; ++$i)
	{
		if($i != 0)
		{
			$str .= ", ";
		}
		$str .= $types[$i + 1] == 0 ? "uintptr_t" : "double";
	}
	$str .= ")>(func)(";
	for ($i = 0; $i != $nargs; ++$i)
	{
		if($i != 0)
		{
			$str .= ", ";
		}
		if ($types[$i + 1] == 0)
		{
			$str .= "args[".$i."]";
		}
		else
		{
			$str .= "reinterpret_int_to_float(args[".$i."])";
		}
	}
	$str .= $types[0] == 0 ? ")" : "))";
	return $str;
}

function pos_to_cpp(int $position): string
{
	if ($position == 0)
	{
		return "nargs";
	}
	else
	{
		return $position - 1;
	}
}

function array_copy(array $a): array
{
	return $a;
}

function recursive_trinary(array& $stack, int $nargs): string
{
	$pos = count($stack);
	if ($pos > $nargs)
	{
		return callsite($stack);
	}
	$stackc = array_copy($stack);
	array_push($stackc, 0);
	if ($pos > 4) // Further arguments don't need to be passed in a specific register (passed on the stack)
	{
		$str = recursive_trinary($stackc, $nargs);
	}
	else
	{
		$indent = str_repeat("\t", 4 + $pos);
		$str = "types[".pos_to_cpp($pos)."] == ffi::VT_INTEGRAL\n$indent? ".recursive_trinary($stackc, $nargs);
		$stackc[$pos] = 1;
		$str .= "\n$indent: ".recursive_trinary($stackc, $nargs);
	}
	return $str;
}

function nargs_case(int $nargs): string
{
	$stack = [];
	return "\t\tcase ".$nargs.":\n\t\t\treturn ".recursive_trinary($stack, $nargs)."\n\t\t\t\t;\n";
}

$fh = fopen("../ffi_call_win_x64.cpp", "w");
fwrite($fh, "// This file was generated by codegen/ffi_win_x64.php\n");
fwrite($fh, "#include \"ffi.hpp\"\n");
fwrite($fh, "#if SOUP_WINDOWS && SOUP_X86 && SOUP_BITS == 64\n");
fwrite($fh, "NAMESPACE_SOUP\n");
fwrite($fh, "{\n");
fwrite($fh, "\tuintptr_t ffi::call(void* func, const ValueType types[/*nargs + 1 (return type)*/], const uintptr_t args[/*nargs*/], size_t nargs)\n");
fwrite($fh, "\t{\n");
fwrite($fh, "\t\tswitch (nargs)\n");
fwrite($fh, "\t\t{\n");
for ($i = 0; $i != $max_args + 1; ++$i)
{
	fwrite($fh, nargs_case($i));
}
fwrite($fh, "\t\t}\n");
fwrite($fh, "\t\tSOUP_THROW(BadCall());\n");
fwrite($fh, "\t}\n");
fwrite($fh, "}\n");
fwrite($fh, "#endif\n");
