name: Build

on: push

jobs:
  ubuntu-24-04:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Build Soup
        run: php build_lib.php

      - name: Build CLI
        run: php build_cli.php

      - name: Run ./soup test
        run: ./CLI/soup test

      - name: Run ./soup bench
        run: ./CLI/soup bench

  ubuntu-22-04:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Build Soup
        run: php build_lib.php

      - name: Build CLI
        run: php build_cli.php

      - name: Run ./soup test
        run: ./CLI/soup test

      - name: Run ./soup bench
        run: ./CLI/soup bench

  debian-10:
    runs-on: [debian-10]
    steps:
      - uses: actions/checkout@v4

      - name: Build Soup
        run: php build_lib.php

      - name: Build CLI
        run: php build_cli.php

      - name: Run ./soup test
        run: ./CLI/soup test

      - name: Run ./soup bench
        run: ./CLI/soup bench

      - name: Upload soup
        uses: actions/upload-artifact@v4
        with:
          name: "Debian 10 and above (X64)"
          path: |
            CLI/soup
            libsoup.a
            libsoupbindings.so

  arm64:
    runs-on: [ARM64]
    steps:
      - uses: actions/checkout@v4

      - name: Build Soup
        run: php build_lib.php

      - name: Build CLI
        run: php build_cli.php

      - name: Run ./soup test
        run: ./CLI/soup test

      - name: Run ./soup bench
        run: ./CLI/soup bench

      - name: Upload soup
        uses: actions/upload-artifact@v4
        with:
          name: "Debian 12 (ARM64)"
          path: |
            CLI/soup
            libsoup.a
            libsoupbindings.so

  macos-13:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Build Soup
        run: php build_lib.php

      - name: Build CLI
        run: php build_cli.php

      - name: Run ./soup test
        run: ./CLI/soup test

      - name: Run ./soup bench
        run: ./CLI/soup bench

      - name: Upload soup
        uses: actions/upload-artifact@v4
        with:
          name: "MacOS (X64)"
          path: |
            CLI/soup
            libsoup.a
            libsoupbindings.dylib

  macos-14:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2

      - name: Build Soup
        run: php build_lib.php

      - name: Build CLI
        run: php build_cli.php

      - name: Run ./soup test
        run: ./CLI/soup test

      - name: Run ./soup bench
        run: ./CLI/soup bench

      - name: Upload soup
        uses: actions/upload-artifact@v4
        with:
          name: "MacOS (ARM64)"
          path: |
            CLI/soup
            libsoup.a
            libsoupbindings.dylib

  windows-latest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure LLVM is up-to-date
        run: choco upgrade llvm

      - name: Build Soup
        run: php build_lib.php

      - name: Build CLI
        run: php build_cli.php

      - name: Run ./soup test
        run: CLI/soup.exe test

      - name: Run ./soup bench
        run: CLI/soup.exe bench

      - name: Upload soup
        uses: actions/upload-artifact@v4
        with:
          name: "Windows (X64)"
          path: |
            CLI/soup.exe
            soup.lib
            soupbindings.dll

  emscripten:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@v13

      - uses: actions/checkout@v4

      - name: Build Soup
        run: php wasm.php

      - name: Ensure files exist
        uses: andstor/file-existence-action@v3
        with:
          files: "bindings/libsoup.js, bindings/libsoup.wasm"
          fail: true

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: "WASM"
          path: |
            bindings/libsoup.js
            bindings/libsoup.wasm
