name: Build

on: push

jobs:
  ubuntu-24-04:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Build Soup
        run: php build_lib.php

      - name: Build CLI
        run: php build_cli.php

      - run: ./CLI/soup test

      - run: ./CLI/soup bench

  ubuntu-22-04:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Build Soup
        run: php build_lib.php

      - name: Build CLI
        run: php build_cli.php

      - run: ./CLI/soup test

      - run: ./CLI/soup bench

  debian-10:
    runs-on: [debian-10]
    steps:
      - uses: actions/checkout@v4

      - name: Build Soup
        run: php build_lib.php

      - name: Build CLI
        run: php build_cli.php

      - run: ./CLI/soup test

      - run: ./CLI/soup bench

      - name: Ensure files exist
        uses: andstor/file-existence-action@v3
        with:
          files: "CLI/soup, libsoup.a, libsoupbindings.so"
          fail: true

      - name: Upload soup
        uses: actions/upload-artifact@v4
        with:
          name: "Debian 10 and above (X64)"
          path: |
            CLI/soup
            libsoup.a
            libsoupbindings.so

  arm64:
    runs-on: [ARM64]
    steps:
      - uses: actions/checkout@v4

      - name: Build Soup
        run: php build_lib.php

      - name: Build CLI
        run: php build_cli.php

      - run: ./CLI/soup test

      - run: ./CLI/soup bench

      - name: Ensure files exist
        uses: andstor/file-existence-action@v3
        with:
          files: "CLI/soup, libsoup.a, libsoupbindings.so"
          fail: true

      - name: Upload soup
        uses: actions/upload-artifact@v4
        with:
          name: "Debian 12 and above (ARM64)"
          path: |
            CLI/soup
            libsoup.a
            libsoupbindings.so

  macos-15-intel:
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v4

      - name: Build Soup
        run: php build_lib.php

      - name: Build CLI
        run: php build_cli.php

      - run: ./CLI/soup test

      - run: ./CLI/soup bench

      - name: Ensure files exist
        uses: andstor/file-existence-action@v3
        with:
          files: "CLI/soup, libsoup.a, libsoupbindings.dylib"
          fail: true

      - name: Upload soup
        uses: actions/upload-artifact@v4
        with:
          name: "MacOS (X64)"
          path: |
            CLI/soup
            libsoup.a
            libsoupbindings.dylib

  macos-14:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2

      - name: Build Soup
        run: php build_lib.php

      - name: Build CLI
        run: php build_cli.php

      - run: ./CLI/soup test

      - run: ./CLI/soup bench

      - name: Ensure files exist
        uses: andstor/file-existence-action@v3
        with:
          files: "CLI/soup, libsoup.a, libsoupbindings.dylib"
          fail: true

      - name: Upload soup
        uses: actions/upload-artifact@v4
        with:
          name: "MacOS (ARM64)"
          path: |
            CLI/soup
            libsoup.a
            libsoupbindings.dylib

  windows-latest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure LLVM is up-to-date
        run: choco upgrade llvm

      - name: Build Soup
        run: php build_lib.php

      - name: Build CLI
        run: php build_cli.php

      - run: CLI/soup.exe test

      - run: CLI/soup.exe bench

      - name: Ensure files exist
        uses: andstor/file-existence-action@v3
        with:
          files: "CLI/soup.exe, soup.lib, soupbindings.dll"
          fail: true

      - name: Upload soup
        uses: actions/upload-artifact@v4
        with:
          name: "Windows (X64)"
          path: |
            CLI/soup.exe
            soup.lib
            soupbindings.dll

  emscripten:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@v13

      - uses: actions/checkout@v4

      - name: Build Soup
        run: php wasm.php

      - name: Ensure files exist
        uses: andstor/file-existence-action@v3
        with:
          files: "bindings/libsoup.js, bindings/libsoup.wasm"
          fail: true

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: "WASM - JS Bindings (Emscripten)"
          path: |
            bindings/libsoup.js
            bindings/libsoup.wasm

  wasi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Clang 20
        run: |
          sudo apt-get update
          sudo apt-get install -y wget lsb-release software-properties-common gnupg

          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20

          # Verify installation
          clang-20 --version

      - name: Setup WASI compilation
        run: |
          wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-30/libclang_rt-30.0.tar.gz
          tar -zxvf libclang_rt-30.0.tar.gz
          sudo cp -r libclang_rt-30.0/wasm32-unknown-wasi /usr/lib/llvm-20/lib/clang/20/lib/wasm32-unknown-wasi

          wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-30/wasi-sysroot-30.0.tar.gz
          tar -zxvf wasi-sysroot-30.0.tar.gz

      - name: Build Soup
        run: rm soup/soup.cpp && php build_lib.php "clang-20 --target=wasm32-wasi --sysroot=wasi-sysroot-30.0 -fno-exceptions"

      - name: Build CLI
        run: php build_cli.php "clang-20 --target=wasm32-wasi --sysroot=wasi-sysroot-30.0 -fno-exceptions -lc++ -lc++abi"

      - name: Ensure files exist
        uses: andstor/file-existence-action@v3
        with:
          files: "CLI/soup"
          fail: true

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: "WASM - CLI (wasi-sdk)"
          path: |
            CLI/soup
